from scripts.benchmark_models import benchmark_models
from scripts.compare_models import compare_models
from scripts.data_preprocessing import load_and_prepare_data
from scripts.model_training import train_all_models